export const INIT_VALUES = [
  {
    title: "0",
    key: "0",
    // children: [
    //   {
    //     title: "0-0",
    //     key: "0-0",
    //     isLeaf: true,
    //     parent: "0",
    //     isAdd: true,
    //   },
    // ],
  },
];

export const SERVICES = [
  {
    id: 118,
    is_available: true,
    name: "Banker",
    value: 118,
    label: "Banker",
  },
  {
    id: 119,
    is_available: true,
    name: "Certified Retirement Counselor",
    label: "Certified Retirement Counselor",
    value: 119,
  },
  {
    id: 120,
    is_available: true,
    name: "Certified Retirement Planning Counselor",
    label: "Certified Retirement Planning Counselor",
    value: 120,
  },
  {
    id: 121,
    is_available: true,
    name: "Retirement Income Certified Professional",
    label: "Retirement Income Certified Professional",
    value: 121,
  },
  {
    id: 122,
    is_available: true,
    name: "Registered Investment Advisor",
    label: "Registered Investment Advisor",
    value: 122,
  },
];

export const ZIPCODE_LIST = [
  {
    available: false,
    city: "Apo",
    code: "09323",
    state: "AE",
    label: "09323(Apo,AE)",
    children: SERVICES,
  },
  {
    add_on_detail_id: 35160,
    add_on_id: 1,
    available: true,
    city: "Jonesboro",
    code: "72405",
    state: "AR",
    value: 35160,
    label: "72405(Jonesboro,AR)",
    zip_id: 35160,
    children: SERVICES,
  },
  {
    add_on_detail_id: 43743,
    add_on_id: 1,
    available: true,
    city: "Napakiak",
    code: "99634",
    state: "AK",
    value: 43743,
    label: "99634(Napakiak,AK)",
    zip_id: 43743,
    children: SERVICES,
  },
  {
    add_on_detail_id: 43675,
    add_on_id: 1,
    available: true,
    city: "Adak",
    code: "99546",
    state: "AK",
    value: 43675,
    label: "99546(Adak,AK)",
    zip_id: 43675,
    children: SERVICES,
  },
  {
    add_on_detail_id: 43676,
    add_on_id: 1,
    available: true,
    city: "Atka",
    code: "99547",
    state: "AK",
    value: 43676,
    label: "99547(Atka,AK)",
    zip_id: 43676,
    children: SERVICES,
  },
  {
    add_on_detail_id: 43682,
    add_on_id: 1,
    available: true,
    city: "Akutan",
    code: "99553",
    state: "AK",
    value: 43682,
    label: "99553(Akutan,AK)",
    zip_id: 43682,
    children: SERVICES,
  },
  {
    add_on_detail_id: 43683,
    add_on_id: 1,
    available: true,
    city: "Alakanuk",
    code: "99554",
    state: "AK",
    value: 43683,
    label: "99554(Alakanuk,AK)",
    zip_id: 43683,
    children: SERVICES,
  },
  {
    add_on_detail_id: 43689,
    add_on_id: 1,
    available: true,
    city: "Chefornak",
    code: "99561",
    state: "AK",
    value: 43689,
    label: "99561(Chefornak,AK)",
    zip_id: 43689,
    children: SERVICES,
  },
  {
    add_on_detail_id: 43690,
    add_on_id: 1,
    available: true,
    city: "Chevak",
    code: "99563",
    state: "AK",
    value: 43690,
    label: "99563(Chevak,AK)",
    zip_id: 43690,
    children: SERVICES,
  },
  {
    add_on_detail_id: 43697,
    add_on_id: 1,
    available: true,
    city: "Cold Bay",
    code: "99571",
    state: "AK",
    value: 43697,
    label: "99571(Cold Bay,AK)",
    zip_id: 43697,
    children: SERVICES,
  },
];

export const MANAGE_ZIPCODE = [
  {
    title: "0",
    key: "0",
    add_on_detail_id: 43743,
    add_on_id: 1,
    available: true,
    city: "Napakiak",
    code: "99634",
    state: "AK",
    value: 43743,
    label: "99634(Napakiak,AK)",
    zip_id: 43743,
    children: [
      {
        title: "0-0",
        key: "0-0",
        isLeaf: true,
        parent: "0",
        isAdd: false,
        zip_id: 43743,
        service: "Banker",
        service_id: 118,
        isFirstServiceCard: true,
      },
      {
        title: "0-1",
        key: "0-1",
        isLeaf: true,
        parent: "0",
        isAdd: false,
        zip_id: 43743,
        service_id: 119,
        service: "Certified Retirement Counselor",
      },
      {
        title: "0-2",
        key: "0-2",
        isLeaf: true,
        parent: "0",
        isAdd: true,
        zip_id: 43743,
        service_id: "",
        service: "",
      },
    ],
  },
];
