export const profiles = [
  {
    id: "1",
    name: "Stevie Burger",
    business: "Burger Financial Advisors",
    location: "Hebron, KY",
    industry: "Finance",
    email: "stevie.burger@burgerfinancial.com",
    phone: "(859) 555-1234",
    avatar: "SB",
  },
  {
    id: "1a",
    name: "Stevie Burger",
    business: "Burger Consulting Group",
    location: "Louisville, KY",
    industry: "Consulting",
    email: "stevie@burgerconsulting.com",
    phone: "(502) 555-2345",
    avatar: "SB",
  },
  {
    id: "1b",
    name: "Stevie Burger",
    business: "Burger Real Estate",
    location: "Cincinnati, OH",
    industry: "Real Estate",
    email: "stevie@burgerrealty.com",
    phone: "(513) 555-3456",
    avatar: "SB",
  },
  {
    id: "2",
    name: "Preeta Rajan",
    business: "Rajan Consulting Group",
    location: "Orlando, FL",
    industry: "Consulting",
    email: "preeta.rajan@rajanconsulting.com",
    phone: "(407) 555-5678",
    avatar: "PR",
  },
  {
    id: "2a",
    name: "Preeta Rajan",
    business: "Rajan Financial Services",
    location: "Tampa, FL",
    industry: "Finance",
    email: "preeta@rajanfinancial.com",
    phone: "(813) 555-6789",
    avatar: "PR",
  },
  {
    id: "2b",
    name: "Preeta Rajan",
    business: "Rajan Marketing Agency",
    location: "Miami, FL",
    industry: "Marketing",
    email: "preeta@rajanmarketing.com",
    phone: "(305) 555-7890",
    avatar: "PR",
  },
  {
    id: "2c",
    name: "Preeta Rajan",
    business: "Rajan Legal Group",
    location: "Jacksonville, FL",
    industry: "Legal",
    email: "preeta@rajanlegal.com",
    phone: "(904) 555-8901",
    avatar: "PR",
  },
  {
    id: "2d",
    name: "Preeta Rajan",
    business: "Rajan Real Estate",
    location: "Fort Lauderdale, FL",
    industry: "Real Estate",
    email: "preeta@rajanrealty.com",
    phone: "(954) 555-9012",
    avatar: "PR",
  },
  {
    id: "2e",
    name: "Preeta Rajan",
    business: "Rajan Insurance Agency",
    location: "St. Petersburg, FL",
    industry: "Insurance",
    email: "preeta@rajaninsurance.com",
    phone: "(727) 555-0123",
    avatar: "PR",
  },
  {
    id: "2f",
    name: "Preeta Rajan",
    business: "Rajan Accounting Services",
    location: "Tallahassee, FL",
    industry: "Accounting",
    email: "preeta@rajanaccounting.com",
    phone: "(850) 555-1234",
    avatar: "PR",
  },
  {
    id: "2g",
    name: "Preeta Rajan",
    business: "Rajan Wellness Center",
    location: "Naples, FL",
    industry: "Healthcare",
    email: "preeta@rajanwellness.com",
    phone: "(239) 555-2345",
    avatar: "PR",
  },
  {
    id: "3",
    name: "Lauren Schaefer",
    business: "Schaefer Legal Group",
    location: "Austin, TX",
    industry: "Legal",
    email: "lauren.schaefer@schaeferlegal.com",
    phone: "(512) 555-5678",
    avatar: "LS",
  },
  {
    id: "4",
    name: "Rebecca Harris",
    business: "Harris Real Estate",
    location: "Danville, CA",
    industry: "Real Estate",
    email: "rebecca.harris@harrisrealestate.com",
    phone: "(925) 555-9012",
    avatar: "RH",
  },
  {
    id: "4a",
    name: "Rebecca Harris",
    business: "Harris Realty Group",
    location: "San Ramon, CA",
    industry: "Real Estate",
    email: "rebecca@harrisrealtygroup.com",
    phone: "(925) 555-7890",
    avatar: "RH",
  },
  {
    id: "5",
    name: "Rebecca Harris",
    business: "Harris Insurance Agency",
    location: "Danville, IL",
    industry: "Insurance",
    email: "rebecca.harris@harrisinsurance.com",
    phone: "(217) 555-3456",
    avatar: "RH",
  },
  {
    id: "6",
    name: "Lauren Schaefer",
    business: "Schaefer Consulting",
    location: "Chicago, IL",
    industry: "Consulting",
    email: "lauren@schaeferconsulting.com",
    phone: "(312) 555-9876",
    avatar: "LS",
  },
  {
    id: "7",
    name: "Lauren Schaefer",
    business: "Schaefer Marketing Agency",
    location: "Denver, CO",
    industry: "Marketing",
    email: "lauren@schaefermarketing.com",
    phone: "(303) 555-4321",
    avatar: "LS",
  },
  {
    id: "8",
    name: "Lauren Schaefer",
    business: "Schaefer Accounting",
    location: "Portland, OR",
    industry: "Accounting",
    email: "lauren@schaeferaccounting.com",
    phone: "(503) 555-8765",
    avatar: "LS",
  },
  {
    id: "9",
    name: "Lauren Schaefer",
    business: "Schaefer Real Estate",
    location: "Seattle, WA",
    industry: "Real Estate",
    email: "lauren@schaeferrealty.com",
    phone: "(206) 555-2345",
    avatar: "LS",
  },
  {
    id: "10",
    name: "Lauren Schaefer",
    business: "Schaefer Financial Planning",
    location: "Boston, MA",
    industry: "Finance",
    email: "lauren@schaeferfinancial.com",
    phone: "(617) 555-6789",
    avatar: "LS",
  },
  {
    id: "11",
    name: "Lauren Schaefer",
    business: "Schaefer Wellness Center",
    location: "Miami, FL",
    industry: "Healthcare",
    email: "lauren@schaeferwellness.com",
    phone: "(305) 555-1234",
    avatar: "LS",
  },
  {
    id: "12",
    name: "Lauren Schaefer",
    business: "Schaefer Design Studio",
    location: "San Diego, CA",
    industry: "Design",
    email: "lauren@schaeferdesign.com",
    phone: "(619) 555-5678",
    avatar: "LS",
  },
];
